import "../styles.css"
import Image from "next/image";
import Ale from "../../../../public/Ohio.png"

export default function WFLWeekly5(){
    return (
        <main className = "min-h-screen bg-[#ffffff]">
            <div className="header">
                <h1 className="title-name">WFL Weekly 5 - Week 6: 
                ScheduleGate</h1>
                <div className="post-meta">
                    Papa Jack Media · Oct. 11
                </div>
                <div className="divider"></div>
                <div className="article">
                    <p dir="ltr"><span>*Taken from a investigative report done by an anonymous journalist*</span></p>
                    <p dir="ltr"><span>We&rsquo;ve arrived at one of the first big blunders of the current WFL Commissioner&rsquo;s reign. The WFL has seen an uptick in ratings this season, as trades are crazier, upsets are more plentiful, and injuries are more devastating. While this does shed a positive light on the beginning of Commissioner Andy Agudelo&rsquo;s tenure thus far, it does not absolve him from carrying out his basic duties and responsibilities as the figurehead for the WFL. In what can only be described as incomprehensible error, we would like to draw your attention to the Divisions side of the WFL.&nbsp;</span></p>
                    <p dir="ltr"><span>A new addition to the WFL, each of the WFL teams were placed in four divisions to start off the league year, resulting in three teams in each. After some fine tuning and naming rights deals, the Cummish, 33176+, sybau, and Trade2Trade were born. And while they might not have had an overwhelmingly league-changing effect on the WFL, GMs have had a more positive than negative opinion on the change, and there is plenty of room for growth. Or at least, there can be, if the Commissioner holds up his end of the bargain. Upon research into divisional play this year, combined with what was told to GMs during the Owner&apos;s Meeting and in league circles, divisional play would occur at the beginning and end of season. This would allow each team to play their division rivals twice, not unlike how the system works in the NFL. And should the schedule reflect those rules, all would be well and good. But the schedule does not reflect those rules. The WFL season schedule is wrong.&nbsp;</span></p>
                    <p dir="ltr"><span>Looking at the season schedule, you will see that WFL teams will play the first three teams on their schedule twice. And if you cross-reference those opening three games with divisional records, what you should see is that each team has played both their division rivals by the time Week 4 begins. And that&rsquo;s the problem, you don&rsquo;t. Four teams had only played one divisional game by that point, meaning that they&rsquo;ll only have competed in three divisional games the whole season. The matchups missing are the second editions of Jack vs. Jonah, and Eric vs. Fabian. Two of the league&rsquo;s biggest and most historic rivalries simply do not have a Game 2. The excitement that these two games bring to the WFL does enough to feed families. Having no second game is catastrophic to league morale, the GMs themselves, and WFL fans everywhere. It also makes a mockery of the WFL Division system as a whole.&nbsp;</span></p>
                    <p dir="ltr"><span>What seems like perhaps a basic mistake on the surface, is compounded by the fact that the Commissioner had weeks if not months before the season began to make sure everything was in order regarding scheduling. And if not even the Commissioner cares enough about the Divisions to make sure they&rsquo;re organized correctly, why should WFL GMs? The response from Commissioner Andy will be telling, and perhaps offer a glimpse into the future on how his tenure at the top will not only affect his legacy, but the very WFL itself.</span></p>
                    <p dir="ltr"><span>And with that, without further ado, it&rsquo;s time to rock n roll.</span></p>
                    <p><br></br></p>
                    <h2 dir="ltr"><span>Biggest Winner:</span></h2>
                    <p dir="ltr"><span>Build the Waller (Eric) - Don&rsquo;t look now, but Build the Waller is sitting in a playoff position after winning three games in a row. Many were quick to dismiss Eric&rsquo;s team after Joe Burrow, Jayden Reed, and even Tyreek Hill suffered major injuries, but yet all his team has done ever since is win. 180 points against a division rival is the most reason success in what has been a stretch of greatness for Eric, who has seen new stars emerge and take his squad to new heights. Dak Prescott is the new Quarterback of this team, and early signs are showing that he could lead this team to places previously thought unreachable. With no more Braelon Allen in the fold, Breece Hall is back to be ing the workhorse we all knew was possible, and Ashton Jeanty has put some early struggles behind him. The real advantage this team might have over all others is at the Tight End position. Jake Ferguson has been beyond excellent thus far, and Darren Waller has turned back the clock to the days of old, allowing Eric to do the same with his team name. We had the chance to talk to Eric about his recent run of success, who told us &quot;The key to the new found success was just trusting instincts and not hitting the panic button immediately. making a trade and spending money where it needs to be spent to get some new personnel in the building and trusting some of the other players that we drafted to come into their roles nicely.&quot; Build the Waller could make a real statement this week by taking down the league&rsquo;s highest scoring team, in Rome wasn&rsquo;t built in a day.</span></p>
                    <h2 dir="ltr"><span>Other Winners:</span></h2>
                    <p dir="ltr"><span>Worse than WHL (Jeremias) - There&rsquo;s a sneaky team sitting in 4th place in the WFL right now that we might have to acknowledge a bit more. That team is Worse than WHL. Trades have brought new life to this team and not only given it one of the league&rsquo;s most feared RB rooms, but also WR depth that could prove very useful later this season. The three-headed monster that is Jonathan Taylor, Christian McCaffrey, and Quinshon Judkins is nothing less than spectacular and has led the way for Worse than WHL&apos;s recent success. If Stefon Diggs and Brian Thomas can continue to round back into form, this team might be an odds on favorite come playoff time. With some of the WFL&rsquo;s top teams in tough matchups this week, we could see Jere&apos;s squad climb even further up the standings should they avoid a disastrous week against a reeling Hall of Fame Youtuber.&nbsp;</span></p>
                    <p dir="ltr"><span>Rico Suave (Johnny) - There is something brewing here in the Rico Suave HQ, and it has all the makings of becoming one of the WFL&apos;s biggest stories this season. Johnny has traded, traded, traded, and traded some more, seeing new faces walk through doors almost every other day in what has been a valiant attempt to claw back into being competitive. It&rsquo;s almost too difficult to try and evaluate this team as it stands, because half the players on the roster could be gone by next week, but what the hell we&rsquo;ll try. Patrick Mahomes has been the one consistent source of optimism and points for this team, as he seems to have regained his form as one of fantasy&rsquo;s top QBs. And while there is a bit of hoping for some lucky breaks with Alvin Kamara &amp; Chuba Hubbard/Rico Dowdle at the starting RB slots, it might just be enough to get the job done. Two of the biggest prizes on this team are Quentin Johnston and the newly acquired Emeka Egbuka. Both have been exceptional this season and show little reason to believe they are going to slow down any time soon. Looking elsewhere on the roster sees Johnny looking for the cards to fall his way and hoping for some lucky rolls of the dice, but if his trades have told you anything, he&rsquo;s just fine with that. This week&rsquo;s matchup with The Bang Bros will be the biggest test thus far in whether this team is a legitimate force going forward.</span></p>
                    <h2 dir="ltr"><span>Biggest Loser:</span></h2>
                    <p dir="ltr"><span>Rome wasn&rsquo;t built in a day (Parker) - Man&hellip; It&rsquo;s hard to not feel bad about what has happened to Rome wasn&rsquo;t built in a day. This team looked like it might be ready to fly towards a potential championship game appearance with how strong it looked in Weeks 1 &amp; 2, but a tough loss in Week 3 to KRAFT YAC &amp; CHEESE has sent this team in a 3 game slide down the standings. Some of this mediocrity can be attributed to bad luck given Rome wasn&rsquo;t built in a day stands far and away as the highest scoring team in the WFL, but also gives up the second most points as well. Now barely hanging on to the last playoff spot, it would be a very good time for Parker&rsquo;s squad to show some fight and get back to winning ways. We asked Parker about his team&apos;s struggles as of recent, but we were not able to reach him unfortunately. This week&rsquo;s matchup against Build the Waller features two teams going in opposite directions. It&rsquo;ll be up to Parker and his guys to stop the bleeding and earn a much needed win.</span></p>
                    <h2 dir="ltr"><span>Other Losers:</span></h2>
                    <p dir="ltr"><span>Cumming&hellip; (Daniel) - Daniel had a golden opportunity to get a win last week in the WFL Weekly Game of the Week against Rico Suave, but his team just didn&rsquo;t have enough in the tank. That&rsquo;s got to be a tough pill to swallow for a Cumming&hellip; team whose journey has been linked to Johnny&rsquo;s squad all season due to both going all in last year to no avail, and starting this season off at a disadvantage. The fact of the matter is that while Johnny has made trade after trade to find a solution, Daniel has not. Sure he&rsquo;s made trades and hasn&rsquo;t just rolled over and died, but the level of activity between both GMs might be just what made the difference this past week in their matchup. The good news for Cumming&hellip; is that they have yet another matchup in the WFL cellar this week with 11th place Marvin&apos;s Room. Let&rsquo;s see if they can fare any better in this one.</span></p>
                    <p dir="ltr"><span>Marvin&apos;s Room (Jack) - Nearly all of the good feelings from Week 4&apos;s victory over Wake and Baker Co. dissipated with last week&rsquo;s loss to KRAFT YAC &amp; CHEESE. Jack&apos;s squad could have had the league leaders on the ropes and almost did, when they took a 1 point lead into Monday Night Football. But the point they scored at the end were too little to late, as Drew&apos;s kicker put the game to bed and sent Marvin&apos;s Room to 1-4. If the GM for this team opened his eyes, locked in, and stopped playing scared, he would be looking at a 2-3 team and still have Michael Pittman along with Rachaad White on this squad. But we don&rsquo;t live in the world of &quot;If&quot;. The facts point to potentially every week starting now as must-win for the defending WFL Champions, and no game is a given. If Marvin&apos;s Room can&rsquo;t get the job done against Cumming&hellip; we might have to start having some uncomfortable conversations about this team.</span></p>
                    <h2 dir="ltr"><span>Donuts! (Sponsored by Tough Cookie Inc.):</span></h2>
                    <p dir="ltr"><span>Yet again, the WFL Bakery is left with just one order for this week&rsquo;s donut delivery. WFL GMs are perhaps getting smarter about their starts and their diets, as we&rsquo;ve seen a lull in the amount of donuts consumed this season. But rest assured, we know they can&rsquo;t help themselves. They can&rsquo;t stay away for long. The day of reckoning will soon arrive, and a tasty treat takeover will unleash itself on the WFL&hellip; Happy eating Daniel!</span></p>
                    <p dir="ltr"><span>🍩 Rashod Bateman (Cumming&hellip;) - Daniel might be unaware, but he&rsquo;s setting a pattern here. He has earned a donut every other week of the season so far, and is now leading the pack with three donuts thus far. This week it was Rashod Bateman who earned Cumming&hellip; their third tasty treat, and simply wasn&rsquo;t a factor with Cooper Rush at QB for the Ravens. A factor that is certainly relevant here at the WFL Bakery is that each donut Daniel has ordered has been cream-filled. Very interesting&hellip;</span></p>
                    <h2 dir="ltr"><span>Ale&rsquo;s Trade to Trade Analysis:</span></h2>
                    <p dir="ltr"><span>*Powered by WussiesGPT*</span></p>
                    <p dir="ltr"><span>Week 6 of the WFL has arrived. The crossroads, as it pertains to trades, gives managers a time to pause. Do you blow up the roster, buy-low on an injured player, or send your letter to Daniel&rsquo;s HQ (Mind you at this point he ASKED for 2 players. He hasn&rsquo;t responded to me)? We don&rsquo;t know the answer. What we do know, at the end of the day, your trade will be rated. Trade to Trade.</span></p>
                    <p dir="ltr"><span>(I got my LV bag with a lil labubu)</span></p>
                    <p dir="ltr"><span>&mdash;&mdash;&mdash;&mdash;</span></p>
                    <p dir="ltr"><span>Trade</span></p>
                    <p dir="ltr"><span>&gt; Parker Gets: Rashee (Fried This) Rice &amp; Elic Ayomanor&nbsp;</span></p>
                    <p dir="ltr"><span>&gt; Johnny Gets: &nbsp;Bill Nye (Jacoby Croskey-Meritt, Zay Flowers and $15 clams to spend on FAAB.&nbsp;</span></p>
                    <p dir="ltr"><span>My first gut reaction to this trade is how FAAB has affected our league. Has it benefited it? Evened the odds? Allowed managers in the middle of the rankings to get some studs? No. It&rsquo;s overspend after overspend (Just ask commish). We really like this trade. Whilst we can laugh at Johnny at selling the house last year, there&rsquo;s no doubt he&rsquo;s turned the ship around. Both managers get pieces they want (requires patience) and Johnny gets $15 to overspend on Lil&rsquo;Jordan from the NYGiants.&nbsp;</span></p>
                    <p dir="ltr"><span>&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;</span></p>
                    <p dir="ltr"><span>Trade&nbsp;</span></p>
                    <p dir="ltr"><span>Jeremias Gets: Xavier Worthy, Chris Olave</span></p>
                    <p dir="ltr"><span>Ale Gets: Cam Skibiddi, Micheal Carter, Tee Higgins</span></p>
                    <p dir="ltr"><span>Trade To Trade:</span><a href="https://youtu.be/X0lz116FEhw?si=kLecvdIq8dy_JedU"><span>&nbsp;</span><span>https://youtu.be/X0lz116FEhw?si=kLecvdIq8dy_JedU</span></a></p>
                    <p dir="ltr"><span>&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;</span></p>
                    <p dir="ltr"><span>Trade</span></p>
                    <p dir="ltr"><span>Jack Gets: Rachaad White &amp; Chris Olave</span></p>
                    <p dir="ltr"><span>Jere Gets: Mike Evans</span></p>
                    <p dir="ltr"><span>Andy: Michael Pittman</span></p>
                    <p dir="ltr"><span>The WFL Weekly Chief Editor gets involved in a 3-team trade! We here at Trade To Trade HQ really like this one, and it feels like it does a solid job of giving everyone a piece they can walk away with. Is there any other player who has been tossed around like Chris Olave? It&rsquo;s the 11-14 targets a game for you. The sweet sweet trade bait. The winner we feel has to be Jere. If Mike Evans can find the chug jug in Tampa and get over his hammy, Baker&rsquo;s HOT, and can benefit from having another WR in his repertoire.&nbsp;</span></p>
                    <p dir="ltr"><span>Trade to Trade: there&rsquo;s nuance here. Nice</span></p>
                    <p dir="ltr"><span>&mdash;&mdash;&mdash;&mdash;-</span></p>
                    <p dir="ltr"><span>2-PIECE (we&rsquo;ll put them both here, as we feel that Bang Bro Andres got the &ldquo;text jack for me&rdquo; text back to back)&nbsp;</span></p>
                    <p dir="ltr"><span>Andres Gets: Baker Mayfield, Jaylen Waddle, JK Dobbins, Zay Flowers, Bill Nye The Science Guy</span></p>
                    <p dir="ltr"><span>Johnny Gets: Emeka Egbuka, Keon Coleman&nbsp;</span></p>
                    <p dir="ltr"><span>Jonah Gets: Jonah, Josh Allen, Drake London, Brashard Smith (lol)</span></p>
                    <p dir="ltr"><span>What a B2B tweet notification, the REID HYDROGEN BOMB hit my iPhone. Let&rsquo;s start with 2 other managers before we dive into the Bang Bro (singular). Johnny and Jonah got some great pieces, but we love what Jonah put together. Jonah gets a guaranteed 25+ QB1 (unless it&rsquo;s against the patriots?) and the second target in the falcons pecking order. I&rsquo;ll leave it to readers to digest who the first is. While Johnny will certainly egg on his buka, can he sustain that season-long with the return of both Godwin AND Evans? Let&rsquo;s see.&nbsp;</span></p>
                    <p dir="ltr"><span>Mr.Andres, the Bang Bro who always seems to criticize any transaction, or accept a transaction that his co-manager didn&rsquo;t approve of? Yeah he made a deal. Whilst he solves his RB problem (somewhat) we don&rsquo;t like what it took to part ways with. An elite QB1, both London and Egbuka, and Andres could&rsquo;ve waited a few more weeks so that Rhamondre fumbles about 8 more times so that TreVeyon gets 14 out of the 20 RB carries on a New England Sunday. Andres&rsquo;s rosters stands well today, but I don&rsquo;t see the point, and I think his RB problem could&rsquo;ve been solved for a lower price. From the manager who always asked &ldquo;why&rdquo; when managers made deals, we ask YOU, why?&nbsp;</span></p>
                    <p dir="ltr"><span>Trade to trade: Jonah/10.&nbsp;</span></p>
                    <h2 dir="ltr"><span>THE WFL HIERARCHY</span></h2>
                    <p dir="ltr"><span>*Proudly sponsored by Tough Cookie Inc. &amp; written by Drew*</span></p>
                    <p dir="ltr"><span>The WFL Hierarchy is proud to be sponsored by Tough Cookie Inc.&rsquo;s NEW Crack, Don&rsquo;t Crumble Series! Don&rsquo;t forget to check-in every week, we&rsquo;ll be rolling out new items throughout the season.&nbsp;</span></p>
                    <p dir="ltr"><span>Featured Cookie of the Week: Build the Double Chocolate Wallernut&nbsp;</span></p>
                    <p dir="ltr"><span>Risers</span></p>
                    <p dir="ltr"><span>Wake and Baker Co. (Jonah)</span></p>
                    <p dir="ltr"><span>I don&rsquo;t think we&rsquo;ve ever seen as much tomfoolery afoot in the league as we have this season. And the beneficiary in every bit of it is Jonah. While his opponents seemingly crumble around him, Jonah has made trades at opportunistic times and been on the right side of injury luck thus far. With new superstars in town between Josh Allen, Drake London, and the emergence of Garrett Wilson as a certified S.T.U.D., Jonah finds himself standing alone atop the WFL Hierarchy.&nbsp;</span></p>
                    <p dir="ltr"><span>Worse than WHL (Jeremias)</span></p>
                    <p dir="ltr"><span>Jeremias claims the crown as our biggest riser for the week, up three spots after acquiring some much needed upside at WR in the form of Xavier Worthy and Mike Evans while offloading what some see as a major fantasy disappointment this season in Tee Higgins. We still have concerns about his team while Brock Bowers and Mike Evans injuries continue to linger but it looks like the &nbsp;2024 WHL champion is playing the long game this season. He&rsquo;s still equipped with a solid core of RBs that can win any week,&nbsp;</span></p>
                    <p dir="ltr"><span>Fallers</span></p>
                    <p dir="ltr"><span>I ❤️ Ohio (Alejandro)</span></p>
                    <p dir="ltr"><span>Another day, another injury ripping the heart out of a WFL team. Just DAYS after trading a considerable amount of depth to acquire Omarion Hampton from Johnny, he winds up on IR. *sigh* Ale attempted to cover up the damage with a short term rental in Michael Carter and perhaps a bounce back from Tee Higgins will leave I ❤️ Ohio bouncing back up the WFL Hierarchy, but we wouldn&rsquo;t count on it. Ale falls four spots and finds himself just out of our top 6.</span></p>
                    <p dir="ltr"><span>The Bang Bros (Andres)</span></p>
                    <p dir="ltr"><span>Some call it brilliance, some call it vision. From our perspective, we&rsquo;ll just call it idiocracy. We are of course talking about Andres&rsquo; decision to blow up his entire roster 6 weeks into the season. We can&rsquo;t say we don&rsquo;t understand it, as starting Treyveon Henderson and RJ Harvey for 6 straight weeks would be enough to drive anyone insane. But the return Andres got for his star-studded WR room and league-best fantasy QB was poor, at best. Such rash decisions find him slipping two spots down the WFL Hierarchy.</span></p>
                    <ol>
                        <li dir="ltr" >
                            <p dir="ltr"><span>1. Wake and Baker Co. (Jonah)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>2. Rome wasn&rsquo;t built in a day (Parker)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>3. Worse than WHL (Jeremias)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>4. Marvin&rsquo;s Room (Jack)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>5. KRAFT YAC &amp; CHEESE (Drew)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>6. andy (Andy)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>7. I ❤️ Ohio (Alejandro)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>8. Build the Waller (Eric)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>9. The Bang Bros (Andres)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>10. Rico Suave (Johnny)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>11. Hall of Fame Youtuber (Fabian)</span></p>
                        </li>
                        <li dir="ltr" >
                            <p dir="ltr"><span>12. Cumming&hellip; (Daniel)</span></p>
                        </li>
                    </ol>
                    <h2 dir="ltr"><span>The Art of a Team Name:</span></h2>
                    <p dir="ltr"><span>One of perhaps the most overlooked, yet important aspects of Fantasy Football has to be the team name that GMs carefully (usually) craft and build their brand around. Some GMs change their team names every week, others pick one and let it ride for forever. There have certainly been some interesting team names this season, so we asked each WFL GM (most were able to respond) what the inspiration behind their current team names are. We also asked questions regarding if they planned on changing their names, how they feel the names in the league have been this year, and if they feel a good or bad team name impacts team performance. Let&rsquo;s see what kinds of tomfoolery our GMs are up to.</span></p>
                    <p dir="ltr"><span>Worse than WHL (Jeremoose) - &quot;Plain and simple: the WFL is simply a worse league than the WHL, I can foresee it changing if the fantasy football gods reward me like the hockey gods did, only time will tell.&quot;</span></p>
                    <p dir="ltr"><span>andy (Andy) - &quot;I think a team name is a reflection of the GM&rsquo;s personality, for me I use it as an opportunity to have control over a game I don&rsquo;t really have control over. It gives me the opportunity to vent. While someone like Jere uses his team name to reflect the state of the league or his team such as The IR and Better Than the WHL. And then the names that have nothing to do with football I think those are to get a couple quick reaction farms and move on. I&rsquo;ve always been proud of the leagues football team names as they are a reflection of our personalities and not a league filled with generic puns based off player names every one has a uniqueness to their name.&quot;</span></p>
                    <p dir="ltr"><span>Rico Suave (Johnny) - &quot;The inspo for my name is based off my best rest running back who helped lead me to a smooth victory vs my opponent last week. I definitely think a bad team name can impact a team&rsquo;s performance, because a bad name could also mean poor creativity from a gm, leading a team to become stale and flat.&quot;</span></p>
                    <p dir="ltr"><span>KRAFT YAC &amp; CHEESE (Drew) - &quot;My inspiration for my team name right now is of course my team captain and known YAC monster, Tucker Kraft. I have split opinions when it comes to teams that constantly change their name. I think that it&rsquo;s perfectly normal to change the name when you acquire a new player or trade away the namesake of your team. But the other managers who change their name without reason clearly lack a team identity and don&rsquo;t show capable leadership to their players.&quot;</span></p>
                    <p dir="ltr"><span>Wake and Baker Co. (Jonah) - &quot;The inspiration for my team name continues to come from top 3 QB in the NFL, Baker Mayfield, who is a renowned icon at Wake and Baker Co. headquarters. We may have traded him for that bum in Buffalo but we expect that Baker&rsquo;s spirit will continue to inspire our organization on the path to a playoff berth.&quot;</span></p>
                    <p dir="ltr"><span>I ❤️ Ohio (Ale) -&nbsp;</span></p>
                    <Image src={Ale} alt="ale."/>
                    <p dir="ltr"><span>&quot;My inspo for the team name.</span></p>
                    <p dir="ltr"><span>After getting a mug from Jonah for secret santa, I have tried to focus my team name on either Clout International or good omens. Me and Eric had the Baltimore thing going on for a few weeks. I love good omens and find teams with consistent names may have the most success.&quot;</span></p>
                    <p dir="ltr"><span>Build The Waller (Eric) - &quot;The shiny new name of our team pays respects to one of the great team names that has ever existed in the Wussies universe. Team name has got to be just as important as the players you draft on draft night. Team name sets the tone. Team name adds aura. Our squad was looking for a new name for a few weeks and we didn&rsquo;t really have the identity until just a few weeks ago.&quot;</span></p>
                    <p dir="ltr"><span>Cumming&hellip; (Daniel) - &quot;My name is inspired by my team&rsquo;s current status as an up and cummer. And I absolutely believe that a team name can affect performance. Every team needs an identity and the team name is one of the most important ways of defining that.&quot;</span></p>
                    <p dir="ltr"><span>Hall of Fame Youtuber (Fabian) - &quot;I think my name stands the test of time, and yet I do think a change is in order. We shall see if the fantasy gods have something in mind.&quot;</span></p>
                    <p dir="ltr"><span>Marvin&rsquo;s Room (Jack) - &quot;The inspiration behind my team&rsquo;s name was forged by my drafted duo of Marvin Harrison &amp; Marvin Mims. While the latter no longer calls my team his home, Marvin Harrison&apos;s unwavering effort and commitment to improvement has made him an integral part of our locker room. Thus, the name will stay the same as long as resides on my team. It also serves as a double-edged sword because I&rsquo;m sad!&quot;</span></p>
                    <h2 dir="ltr"><span>Papa&rsquo;s Picks:</span></h2>
                    <h2 dir="ltr"><span>WFL Weekly Game of the Week: Rico Suave (Johnny) vs. The Bang Bros (Andres)</span></h2>
                    <ul>
                        <li dir="ltr" >
                            <p dir="ltr"><span>With many options to choose from this week for the WFL Weekly Game of the Week, we turned to the people to see who they thought was worthy of the honor. In an overwhelming majority, WFL GMs were firmly in favor of Rico Suave vs. The Bang Bros as this week&rsquo;s must-see matchup. One GM described the bout as one &quot;with a rich history&quot;, while another perfectly encapsulated the feelings surrounding this game, stating that these GMs had &quot;Two teams with a lot to prove and a lot to lose&quot;. And all of this was gathered BEFORE The Bang Bros took a chainsaw to their team&rsquo;s foundation. To say this week&rsquo;s game between Johnny &amp; Andres has shifted into maximum overdrive would be an understatement, as now both WFL GMs are sporting squads that are almost entirely unrecognizable from the start of the season. As detailed earlier, Johnny has done an admirable job at attempting to trade himself to the top, and could be beginning to see the fruits of his labor. When asked about the matchup and his opponent this week, he told us &quot;Honestly Mr. Reid, this matchup is what I believe is what determines whether I&rsquo;m actually a competitive team, or if my last two weeks have been luck. Andres is no weak opponent, but his QB is throwing my WR touchdowns now so I think I have solid odds.&quot; Andres seemingly had enough of the boom-or-bust run his team was on, and completely cleaned house. When we sat down with him to ask his thoughts on this week&rsquo;s matchup and his opponent, he broke it down quite simply for us, stating &quot;It&rsquo;s anyone&rsquo;s game. This week will not define my future. The decisions that both of us made are with dreams of what lies ahead.&quot; Andres also had nothing but praise for his opponent, calling him &quot;Big Brain. (He) certified yapped himself into having a decent team. He (like myself) will be a surprising playoff candidate now?&quot; The energy surrounding this game is off the charts. You can practically feel the intrigue and excitement in the air as two teams with a lot to prove get ready to bring their absolute best. Johnny has certainly turned many of his doubters into believers, and made preseason predictions look very foolish in the process. Can he incredibly claw his way back to .500 and establish himself as a dark horse in this league? Andres certifiably put his stamp on The Bang Bros team, and is truly the captain of his fate now as he tries to earn his way towards his first solo playoff berth. He set fire to the roster, but will a phoenix rise from the ashes? We find out the answer to both questions in a few short days.</span></p>
                        </li>
                    </ul>
                    <h3 dir="ltr"><span>Upset Watch of the Week: Wake and Baker Co. (Jonah) vs. KRAFT YAC &amp; CHEESE (Drew)</span></h3>
                    <ul>
                        <li dir="ltr" >
                            <p dir="ltr"><span>We came oh so close to predicting yet another upset last week, as KRAFT YAC &amp; CHEESE was just able to scrape out a win against Marvin&apos;s Room. But with little other options, the only right move to make here is to run it back. Wake and Baker Co. have a revamped roster and look to test out their might this week as Josh Allen is the new captain of Jonah&rsquo;s squad. Jaylen Waddle is out, and Drake London is in, providing a boost or downgrade to the WR core depending on who you&rsquo;re talking to. Jonah will hope that Penix plays more consistently and maximizes London&rsquo;s skillset this week and going forward. While Drew does get his favorite Tight End back this week in Tucker Kraft, Nico Collins &amp; Jordan Mason on bye provide a couple of holes in the lineup that we&rsquo;re skeptical Troy Franklin &amp; Malik Washington can fill. Drew also is having to put a lot of trust in Calvin Ridley following his season-best performance last week against the Cardinals. Does Jonah&rsquo;s squad have what it takes to get back on track with a big victory? Or will Drew slam the door shut yet again on another upset-hopeful team?</span></p>
                        </li>
                    </ul>
                    <p dir="ltr"><span>Predictions: (Last Week&rsquo;s results: 4-2 😌</span></p>
                    <p dir="ltr"><span>20-10 overall)</span></p>
                    <p dir="ltr"><span>#11 Marvin&apos;s Room (Jack) ✅ vs. #12 Cumming&hellip; (Daniel)</span></p>
                    <p dir="ltr"><span>#4 Worse than WHL (Jere) ✅ vs. #9 Hall of Fame Youtuber (Fab)</span></p>
                    <p dir="ltr"><span>#5 Build the Waller (Eric) ✅ vs. #6 Rome wasn&rsquo;t built in a day (Parker)</span></p>
                    <p dir="ltr"><span>#1 KRAFT YAC &amp; CHEESE (Drew) vs. #8 Wake and Baker Co. (Jonah) ✅</span></p>
                    <p dir="ltr"><span>#2 I ❤️ Ohio (Ale) vs. #3 andy (Andy) ✅</span></p>
                    <p dir="ltr"><span>#10 Rico Suave (Johnny) vs. #7 The Bang Bros (Andres) ✅</span></p>
                    <div className="divider"></div>
                    <p dir="ltr"><span>Divisional Standings</span></p>
                    <p dir="ltr"><span>(Divisional Record in parentheses)</span></p>
                    <p dir="ltr"><span>Cummish Division</span></p>
                    <p dir="ltr"><span>#1 KRAFT YAC &amp; CHEESE (Drew): 4-1 (1-1)</span></p>
                    <p dir="ltr"><span>#3 fent folding (Andy): 4-1 (2-0)</span></p>
                    <p dir="ltr"><span>#12 Cumming&hellip; (Daniel): 1-4 (0-2)</span></p>
                    <p dir="ltr"><span>33176+ Division</span></p>
                    <p dir="ltr"><span>#7 The Bang Bros (Andres): 2-3 (1-1)&nbsp;</span></p>
                    <p dir="ltr"><span>#8 Wake and Baker Co. (Jonah): 2-3 (1-1)</span></p>
                    <p dir="ltr"><span>#11 Marvin&apos;s Room (Jack): 1-4 (1-1)</span></p>
                    <p dir="ltr"><span>sybau Division</span></p>
                    <p dir="ltr"><span>#2 I ❤️ Ohio (Alejandro): 4-1 (2-0)</span></p>
                    <p dir="ltr"><span>#5 Build The Waller (Eric): 3-2 (1-1)</span></p>
                    <p dir="ltr"><span>#9 Hall of Fame Youtuber (Fabian): 2-3 (0-2)</span></p>
                    <p dir="ltr"><span>Trade2Trade Division</span></p>
                    <p dir="ltr"><span>#4 Worse than WHL (Jeremias): 3-2 (1-1)</span></p>
                    <p dir="ltr"><span>#6 Rome wasn&rsquo;t built in a day (Parker): 2-3 (2-0)</span></p>
                    <p dir="ltr"><span>#10 Rico Suave (Johnny): 2-3 (0-2)</span></p>
                    <p dir="ltr"><span>A big shoutout to our sponsors Tough Cookie Inc. and WussiesGPT for helping the Donut section &amp; Trade to Trade be what they are today, and to Drew for his power rankings!</span></p>
                    <p dir="ltr"><span>If you or someone you know would like to be a sponsor for WFL Weekly, let us know and we&rsquo;ll give you some options on where you can showcase your brand, company, or organization!</span></p>
                    <p dir="ltr"><span>Additionally, if you have your own ideas for columns, one offs, or weekly installments, speak to Chief Editor Jack Reid for more information!</span></p>
                    <p dir="ltr"><span>The only good luck that we here at WFL Weekly wish you, is good luck with injuries. Everything else is up to the higher powers.</span></p>
                    <p dir="ltr"><span>*Note from the Editor*: Big thank you to Andy &amp; Drew on the WFL Weekly Website team, you guys rock.</span></p>
                    <p><br></br></p>
                    <p><br></br></p>
                </div>
            </div>
        </main>
    )
}